import { ConfigurationSchema } from './types';

export const DEFAULT_CONFIGURATION = Object.freeze<ConfigurationSchema>({
  schemaVersion: 1,

  skipReleaseNotes: false,

  jpdbApiToken: '',
  jpdbBlacklistDeck: 'blacklist',
  jpdbNeverForgetDeck: 'never-forget',
  jpdbForqDeck: 'forq',
  jpdbAddToForq: false,
  jpdbUseTwoGrades: false,
  jpdbRotateFlags: false,
  jpdbRotateCycle: false,
  jpdbDisableReviews: false,
  jpdbReviewNothing: { key: '', code: '', modifiers: [] },
  jpdbReviewSomething: { key: '', code: '', modifiers: [] },
  jpdbReviewHard: { key: '', code: '', modifiers: [] },
  jpdbReviewOkay: { key: '', code: '', modifiers: [] },
  jpdbReviewEasy: { key: '', code: '', modifiers: [] },
  jpdbReviewFail: { key: '', code: '', modifiers: [] },
  jpdbReviewPass: { key: '', code: '', modifiers: [] },
  jpdbRotateForward: { key: '', code: '', modifiers: [] },
  jpdbRotateBackward: { key: '', code: '', modifiers: [] },

  useLegacyHighlighter: false,
  skipFurigana: false,

  enableAnkiIntegration: false,
  ankiUrl: 'http://localhost:8765',
  ankiProxyUrl: '',
  ankiMiningConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  ankiBlacklistConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  ankiNeverForgetConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  ankiReadonlyConfigs: [],

  contextWidth: 1,
  hidePopupAutomatically: true,
  hidePopupDelay: 500,
  hideAfterAction: true,

  showPopupOnHover: false,
  touchscreenSupport: false,
  disableFadeAnimation: false,

  parseKey: { key: 'P', code: 'KeyP', modifiers: ['Alt'] },
  showPopupKey: { key: 'Shift', code: 'ShiftLeft', modifiers: [] },
  showAdvancedDialogKey: { key: '', code: '', modifiers: [] },
  lookupSelectionKey: { key: 'L', code: 'KeyL', modifiers: ['Alt'] },
  addToMiningKey: { key: '', code: '', modifiers: [] },
  addToBlacklistKey: { key: '', code: '', modifiers: [] },
  addToNeverForgetKey: { key: '', code: '', modifiers: [] },

  // Word Colors with default values
  'jpdb-word-color': '#FFFFFF',
  'unparsed-color': '#808080',
  'not-in-deck-color': '#FFFFFF',
  'locked-color': '#A0522D',
  'redundant-color': '#808080',
  'new-color': '#FF4500',
  'learning-color': '#4169E1',
  'known-color': '#228B22',
  'never-forget-color': '#9370DB',
  'due-color': '#FFD700',
  'failed-color': '#DC143C',
  'suspended-color': '#696969',
  'blacklisted-color': '#B0B0B0',
  'misparsed-color': '#FF0000',

  // Button Colors with default values
  'add-button-color': '#22c55e',
  'never-forget-button-color': '#ff4500',
  'blacklist-button-color': '#b0b0b0',
  'nothing-button-color': '#ff69b4',
  'something-button-color': '#ffd700',
  'hard-button-color': '#38bdf8',
  'okay-button-color': '#38bdf8',
  'easy-button-color': '#9370db',
  'pass-button-color': '#4FA825',
  'fail-button-color': '#FF3B3B',

  selectedDecks: [],
  selectedMiningDeck: '',

  customWordCSS: '',
  customPopupCSS: '',
});
